### ISSUE TITLE
data.sql Full Profil fehlerhaft

### ISSUE THREAD

**Issue by wexstorm** [FriendsOfREDAXO/tinymce5#15]
Erstmal vielen Dank für das tolle Plugin. Klappt schon sehr gut.
Leider ist das full Profil in o.g. Datei fehlerhaft. Es sind andere callbacks eingefügt, als wirklich vorhanden sind. Das führt beim Callback 
`rex5_setup_callback`
zu einer JS-Fehlermeldung.

**Comment by ynamite** [comment]
Kann ich bestätigen. Die Ursprungs-Datei tinymce5_profiles.js ist Korrekt, wird aber beim Speichern eines Profils mit falschen Callbacks überschrieben.

**Comment by TobiasKrais** [comment]
Ist der Bug noch aktuell oder wurde das inzwischen behoben?
