### ISSUE TITLE
Bilderauswahl im Editor

### ISSUE THREAD

**Issue by wexstorm** [FriendsOfREDAXO/tinymce5#16]
Das generelle Problem bei TinyMCE waren schon immer die Pfade. 
Im alten Editor wurde dafür extra ein Media Manager Profil angelegt und dafür benutzt.
Ich habe dies nun auch in der Datei tinymce5_rex.js in Zeile 41 angepasst:
```
//const mediaSrcPath = (!typeof media_type === 'undefined') ? mediaManagerPath : mediaPath;
const mediaSrcPath = 'index.php?rex_media_type=tinymceimg&rex_media_file=';
```
Damit werden die Pfade auch bei Projekten mit Unterordnern usw. sowie im Editor direkt korrekt angezeigt.
Bitte mal darüber nachdenken.

**Comment by DagmarU** [comment]
Wenn man ein Bild mit dem Editor (V 1.2.2) einbindet, wird es im Frontend nicht angezeigt. Die Verlinkung erfolgt mit ../media. Bilder, die in anderen Modulen mit /media verlinkt wurden, werden angezeigt.

**Comment by eaCe** [comment]
https://github.com/FriendsOfREDAXO/tinymce5/commit/6e502cc55479ef5988cd9ae1e12af7bcdad6d7d5
