### ISSUE TITLE
Fenster springt bei Klick an den Anfang

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/tinymce5#17]
Erstmal vielen Dank, freue mich riesig, dass es ein Tinymce 5 Addon gibt.

Ein kleines Problem ist mir aufgefallen: beim Klick auf bestimmte Buttons im Editor springt das Browserfenster ganz nach oben (zum Beispiel Button "Quellcode anzeigen"). 

Wenn man das geöffnete Fenster/Modal dann wieder schliesst, versucht Tiny offenbar zurück zum Editor zuspringen, verfehlt allerdings den Zielort (bei mir im aktuellsten Firefox) um ein paar hundert Pixel. 

Betrifft scheinbar nur Buttons die ein neues Fenster/Modal öffnen.

**Comment by skerbis** [comment]
Kann ich aktuell nicht bestätigen

**Comment by ynamite** [comment]
Hängt möglicherweise mit mblock zusammen. Ich teste nochmal!

**Comment by skerbis** [comment]
und? @ynamite

**Comment by ynamite** [comment]
@skerbis bei mir vor allem im Verbund mit dem `full` Profil und mblock nach wie vor ziemlich buggy (böse gesagt unbrauchbar, leider), auch mit der aktuellsten Version aus dem Installer. Gerade extra für dich getestet.

Fenster springt nach oben/unten wenn ein Dialog von Tiny geöffnet wird, manchmal springt es mehr oder weniger an die korrekte Stelle zurück, öfter aber nicht, Toolbar verschwindet bzw. die gesamte Seite friert ein, je nachdem was man klickt/macht. Wenn das passiert, hilft teilweise nicht mal mehr ein Refresh/Reload, erst wenn man den aktuellen Artikel verlässt und neu aufruft, lässt sich der Editor wieder einigermassen verwenden. 

Dass du das nicht nachstellen kannst, verwundert mich sehr. Ich brauche wirklich nix spezielles zu tun, ein paar mal rumklicken, mblock verschieben usw.. Nach kurzer Zeit ist Schluss mit lustig. 

Der Knopf "Medium einfügen" führt bei mir nach dem Einfügen zu Folgendem: Toolbar des oberen Editors ist weg und kann auch nicht wieder geholt werden. Editor oben ohne mblock, Editor unten mit mblock.
Wenn ich danach im unteren etwas ändere, verschwindet die Toolbar unten und erscheint oben dafür wieder.

<img width="736" alt="Bildschirmfoto 2021-12-01 um 17 07 57" src="https://user-images.githubusercontent.com/1733051/144269954-b9f0ab42-9c80-4ae6-b1b9-4ba6a876c5d7.png">

Vielleicht liegt es an einer Kombination mit den Addons die ich verwende,

**Comment by TobiasKrais** [comment]
Kann ich auch nicht nachvollziehen. @ynamite du vermutest, dass es an einer Kombi von Addons liegt. Kannst du das durch deaktivieren anderer Addons eingrenzen?

**Comment by ynamite** [comment]
@TobiasKrais Möglich wär's aber wirklich vermuten tu ich's nicht. Wenn dann hätte ich mform/mblock vermutet. Wüsste nicht, welches Addon da sonst reinfummeln könnten. Ich probier nochmal!

**Comment by alexwenz** [comment]
Liegt an den Zeilen

`
body.tox-dialog__disable-scroll {
    overflow: visible!important;
}`

in der tinymce5.css.

Wenn das raus ist, springts nicht mehr, man kann aber halt scrollen, wenn man sich im Modal befindet.

Die Klasse wird vom Original-TinyMCE-Theme JS leider auf den body und nicht aufs html gelegt. Das wäre besser...

**Comment by TobiasKrais** [comment]
Die tinymce5.css wird doch nur auf den TinyMCE Backend Seiten nachgeladen und nicht in anderen Artikeln, wie z.B. die Struktur? https://github.com/FriendsOfREDAXO/tinymce5/blob/4fa9f328a4a608b7bec89811164bf7b3a99c43c1/lib/TinyMCE5/Provider/TinyMCE5AssetsProvider.php#L23-L25

**Comment by alexwenz** [comment]
Stimmt! war schon spät für mich gestern...

Liegt an den Stilen, die für den html-Tag über die be-style-CSS-Datei kommen.

Wenn ich

`html {
    height: auto;
    min-height: 100%;
    overflow-y: auto;
}`

in die tinymce5_rex_skin.css packe, ist das Problem weg. Seiteneffekte habe ich bisher noch keine feststellen müssen.

Könnte das jemand auch nochmal testen?

**Comment by TobiasKrais** [comment]
Getestet. Ja, bei mir funktioniert der Fix auch ohne Nebenwirkungen. Hab ihn mal übernommen. Herzlichen Dank!

**Comment by skerbis** [comment]
Getestet. 👍🏻 Top Lösung

**Comment by TobiasKrais** [comment]
Dann mach ich mal ein Release. Danke euch!
