### ISSUE TITLE
Editor fügt <head> und <body> ein

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/tinymce5#19]
Wie schon der Titel des Issues sagt, fügt ein Editor bei meiner Installation
```
<!DOCTYPE` html>
<html>
<head></head>
<body>
```
Und am Ende des Blocks werden die offenen Tags geschlossen.

**Comment by eaCe** [comment]
Das liegt am "fullpage" Plugin im full Profil. Einfach löschen

**Comment by skerbis** [comment]
Danke @TobiasKrais
