### ISSUE TITLE
Imkompatibilität mit TinyMCE4

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/tinymce5#20]
Wenn das tinymce5 Addon installiert ist lädt der tinymce4 Editor nicht mehr. Wird das tinymce5 Addon deaktiviert, funktioniert der Editor wieder korrekt.

**Comment by skerbis** [comment]
Denke, dass man entweder den einen oder den anderen verwenden sollte

**Comment by TobiasKrais** [comment]
Dann muss es in die package.yml. Ich weiß gerade nur nicht wie man das notiert, sonst würde ich einen PR machen.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/tinymce5/commit/731e9a29508a95b7b269059a28abb54a917d9098

**Comment by TobiasKrais** [comment]
Danke!
