### ISSUE TITLE
Nach speichern des Profils: Uncaught ReferenceError: rex5_setup_callback is not defined

### ISSUE THREAD

**Issue by godsdog** [FriendsOfREDAXO/tinymce5#21]
Moin, wenn ich das Profil speichere, wird der TinyMCE nicht mehr geladen.

Folgendes erscheint in der Console:
`Uncaught ReferenceError: rex5_setup_callback is not defined`

Ein Reinstallieren des Addons behebt das Problem.

Redaxo: 5.11.0 im Unterordner
PHP: 7.2.30

**Comment by skerbis** [comment]
Sollte in Beta 4 kein Problem mehr darstellen
