### ISSUE TITLE
Editor schreibt komplett HTML in die value

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/tinymce5#23]
Der Editor speichert ab:

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<p>Die gew&uuml;nschte Seite ist nicht vorhanden.</p>
</body>
</html>
```

aber abspeichern sollte er doch nur

```
<p>Die gew&uuml;nschte Seite ist nicht vorhanden.</p>

```

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/tinymce5/releases/tag/1.0.0-beta4

**Comment by alxndr-w** [comment]
Ist in 1.0.0-beta5 wieder so :(

**Comment by skerbis** [comment]
@alxndr-w Das Fullpage Plugin sollte eigentlich nicht geladen sein. Hast du eine frische Installation durchgeführt oder war da noch ein altes Profil?

**Comment by alxndr-w** [comment]
Frische Installation

**Comment by skerbis** [comment]
und Fullpage ist wieder da?

**Comment by alxndr-w** [comment]
das Plugin selbst wird im Profil nicht aufgerufen, dennoch hatte ich doctype, html und co. im Code.

**Comment by alxndr-w** [comment]
Das Profil ist angelegt, es muss jedoch erst 1x gespeichert werden, damit es wirkt.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/tinymce5/commit/c2e13b8669e9cc8f65a11e918e090441ce4b6202
