### ISSUE TITLE
Mehr Profile mit installieren

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/tinymce5#27]
in der R4-Fassung wurden soweit ich das überblicken kann verschiedene Profile mitgeliefert (mini/light, standard), statt nur einem "full"-Profil. Das beizubehalten fände ich gut, dann geht's schneller, den TinyMCE einzubauen.

**Comment by eaCe** [comment]
Dazu - wenn man das Full-Profil verändert wird das immer über die JS-Datei in den assets überschrieben.
Könnt ihr das nachvollziehen?

**Comment by alexwenz** [comment]
Hmm. Ich habe auch das Problem, dass bei einem Update das full-Profil alle anderen angelegten Profile "überlagert". D.h. obwhl z.B. das Profil "headline" aktiviert ist, erscheint das full-Profil. Bisherige Lösung ist: nochmal in die anderen Profile gehen und abspeichern. Danach wird es wieder korrekt initialisiert.

**Comment by eaCe** [comment]
Genau, nach install oder update muss man TinyMCE5ProfilesCreator::profilesCreate() aufrufen nachdem `tinymce5_profiles.js` kopiert wurde.

**Comment by TobiasKrais** [comment]
Hab mal ein light Profil hinzugefügt. Wie viele Profile wären denn gewünscht?

**Comment by skerbis** [comment]
Ich denke man kann jetzt closen. Bei Bedarf wieder öffnen
