### ISSUE TITLE
Inserting images or links sometimes crashes the editor

### ISSUE THREAD

**Issue by 5in4** [FriendsOfREDAXO/tinymce5#32]
I am running 1.0.0-beta7 on redaxo 5.11.1.

Sometimes, when trying to insert an image or a link, the popup appears for a fraction of a second and then closes immediately. After that, the whole page is frozen. It seems to be broken in a very unique way, because some interaction with elements on the ui is still possible, but scrolling for example is locked.

This seems to happen more reliably, when the viewport is very small, e.g. 1148x549. I have a suspicion that there might be a problem with positioning the modals.

Any advice is appreciated, as there seems to be no console output or anything. Happy to support with debugging.

**Comment by DagmarU** [comment]
Bei mir tritt der oben beschriebene Effekt auch auf. Beim Einfügen von Bildern und beim Anzeigen des Quellcodes. Es passiert auch, wenn der viewport deutlich größer ist als oben angegeben.
Redaxo 5.13.1
Vivaldi 5.0.2497.26 und Firefox 95.0
PHP 7.4.26 und 7.3.33

**Comment by TobiasKrais** [comment]
Ich kann den Fehler leider nicht nachstellen. Könnt ihr es mit dem aktuellen Release verlässlich nachstellen?

**Comment by skerbis** [comment]
Habe es auch noch mal getestet. Diesen Fehler kann ich auch nicht reproduzieren.

**Comment by DagmarU** [comment]
Hallo,
nein, nun stürzt nichts mehr ab. Alles funktioniert bestens. 
Vielen Dank für eure Arbeit!
