### ISSUE TITLE
Medienpool - Deteitypen nicht beschränken

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/tinymce5#38]
Meiner  Meinung nach sollte man die Medientypen beim Auswählen für einen Link nicht beschränken, siehe:

https://github.com/FriendsOfREDAXO/tinymce5/blob/7ef68b2545e8f0f274db280e8aa658893bed65ea/pages/insertlink.php#L3

**Comment by suspa** [comment]
sehe ich auch so, konnte heute kein pdf auswählen, und das nachdem ich mir solche Mühe gemacht habe, das profil anzulegen

**Comment by alexwenz** [comment]
Habe ich rausgenommen. Danke!

**Comment by niklasschoberth** [comment]
Ich habe das Problem bei einem bereits erstelltem Link, wenn ich diesen ändern möchte öffnet sich der Medienpool an der Stelle, wo der Link bisher gesetzt war, allerdings sind die Medientypen dann erneut beschränkt. Erst wenn ich vom Medienpool auf die Strukturübersicht und wieder zurück wechsle, kann ich alle Medientypen auswählen.
Wenn ich einen komplett neuen Link erstelle funktioniert alles völlig problemlos, wie gesagt, das Problem tritt nur bei bereits gesetzten Links auf, wenn man sie editieren möchte.
