### ISSUE TITLE
Bilder werden mit ../media statt /media eingefügt

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/tinymce5#40]
... das führt zu Problemen wenn YRewrite aktiviert ist. /media wird von allen anderen Editoren verwendet.

**Comment by TobiasKrais** [comment]
Bisherige Forschungen haben ergeben, dass erst beim Speichern des Blocks die beiden Punkte vorangesetzt werden.

**Comment by eaCe** [comment]
@TobiasKrais kannst du mal testen ob es einen Unterschied macht, wenn du in deinem Profil folgendes hinzufügst:

relative_urls : false,
remove_script_host : true,
document_base_url : "/",
convert_urls : true,

**Comment by TobiasKrais** [comment]
Ja, kann ich bestätigen. Damit funktioniert es korrekt.

**Comment by TobiasKrais** [comment]
Hab mal einen Fix programmiert, das den Fehler bei künftigen Neuinstallationen behebt. Aber wie machen wir das bei alten Installationen? Sollen wir die Profile beim Update anpassen?

**Comment by eaCe** [comment]
Ich denke bei einem Update sollte man die anderen Profile nicht anfassen.

**Comment by TobiasKrais** [comment]
Hab grad ein Release gemacht. Es gibt für den Nutzer keine Möglichkeit den Fehler zu beheben außer man deinstalliert das Addon.

**Comment by eaCe** [comment]
Alles klar, danke!

**Comment by TobiasKrais** [comment]
Danke noch für deine Hilfe!
