### ISSUE TITLE
Umlaute werden leider wieder gewandelt, obwohl es im Profil deaktiviert war

### ISSUE THREAD

**Issue by metaphon** [FriendsOfREDAXO/tinymce5#41]
Bei den Editor Profile > Profile-Optionen habe ich definiert:
`entity_encoding: 'raw',`

Das klappte bis zur Version 1.2.2.

Aber in der aktuellen Version 1.2.3 werden Umlaute wieder in umgwandelt.

`ä zu &auml;`

Wird entity_encoding nicht mehr unterstützt?

**Comment by alexwenz** [comment]
Hi! Ich kann das hier nicht nachstellen:

Installierte Version 1.2.3, Profil "full" um die Zeile

`entity_encoding : "raw",`

erweitert. Ergebnis:

`<h2 style="text-align: center;">äüößWelcome to the TinyMCE Cloud demo!</h2>`

**Comment by metaphon** [comment]
Ja, das erneute Speichern hat geholfen!
