### ISSUE TITLE
Bisherige Profile werden nur durch erneutes Speichern initialisiert

### ISSUE THREAD

**Issue by metaphon** [FriendsOfREDAXO/tinymce5#42]
Bei einem Update über den Installer werden die Profile nicht richtig initialisiert. Erneutes Speichern des Profil löst das Problem.

**Comment by eaCe** [comment]
Das hatte ich hier auch schon festgestellt: https://github.com/FriendsOfREDAXO/tinymce5/issues/27

**Comment by TobiasKrais** [comment]
Sollte hiermit behoben sein: https://github.com/FriendsOfREDAXO/tinymce5/commit/ed80dbb66e6df1e347dbc4ca99e3b0d0db4322fc

**Comment by TobiasKrais** [comment]
Ne, reicht doch nicht aus. Da muss noch mehr geändert werden.

**Comment by eaCe** [comment]
Wurd von @TobiasKrais hier behoben: https://github.com/FriendsOfREDAXO/tinymce5/commit/2b290c5e71f2c1b84cc02d8f3961175726a83ab5

**Comment by TobiasKrais** [comment]
Hat es bei dir beim Update das Profil aktualisiert?

**Comment by eaCe** [comment]
Ah, nein noch nicht :|

**Comment by eaCe** [comment]
@TobiasKrais ich denke das Problem ist, dass der Assets-Ordner erst nach dem Update kopiert wird.
Einen EP, der danach ausgeführt wird, konnte ich nicht finden.
Man könnte ein Flag in der Addon-Config setzen. Also bei Update die Flag auf false setzen und in der boot.php auf true, wenn man die Profile neu installiert hat, diesen schritt dann überspringen wenn die Flag auf true steht...

**Comment by TobiasKrais** [comment]
Warte mal, das hat doch @skerbis im CKE5 gelöst. Das kopier ich schnell mal rüber.

**Comment by eaCe** [comment]
Ja genau so dachte ich mir das :) nicht schön, funktioniert aber hoffentlich

**Comment by alexwenz** [comment]
Nach einem Reinstall über "AddOns" ist das Problem noch da.  D.h. man muss wieder in die Profile rein und abspeichern.

**Comment by TobiasKrais** [comment]
Fix ist jetzt drin: https://github.com/FriendsOfREDAXO/tinymce5/commit/4fa9f328a4a608b7bec89811164bf7b3a99c43c1
