### ISSUE TITLE
Nach übernehmen oder speichern wird TinyMCE nicht mehr angezeigt

### ISSUE THREAD

**Issue by LAnnika** [FriendsOfREDAXO/tinymce5#45]
Wird TinyMCE in einem Modul oder auf einer AddOn-Page verwendet werden beim ersten Öffnen alle Bedienelemente korrekt angezeigt. Nach dem Speichern, bzw. übernehmen, wird nur noch die Textarea mit dem HTML Code angezeigt. Das Problem tritt z.B. im Global Settings AddOn auf, aber auch in eigenen AddOns, die den Editor verwenden.

Getestet mit TinyMCE 1.2.11 und diversen redaxo Versionen von 5.11.1 - 5.13

Das Problem gab es schon im tinymce4, dort konnte man es aber durch tinymce.remove() und tinymce.init() im rex:ready umgehen - das geht jetzt nicht mehr, beim init kommt die JavaScript Meldung  "NS_ERROR_UNEXPECTED: " in theme.min.js:9

**Comment by eaCe** [comment]
Das ist kein Tiny-Problem, in dem Falle ein Global-Settings-Problem

**Comment by TobiasKrais** [comment]
@LAnnika Hast du die aktuellste Version der Addons installiert?

**Comment by TobiasKrais** [comment]
Soweit ich das sehe kann man den Issue schließen. Falls noch Bedarf ist, bitte nochmals öffnen.
