### ISSUE TITLE
Text-Link zu einer PDF Datei aus dem Medienpool nicht nachträglich editierbar

### ISSUE THREAD

**Issue by brandes-webdesign** [FriendsOfREDAXO/tinymce5#47]
Wenn ich im Tiny 5 Editor einen Text-Link zu einer PDF Datei aus dem Medienpool nachträglich bearbeiten möchte, dann klappt dies nicht. Ich kann kein PDF Dateien mehr auswählen im Medienpool sondern nur Bilder.

Es erscheint folgende Fehlermeldung: 
"Ansicht beschränkt auf Dateien vom Typ: jpg,jpeg,png,gif,bmp,tiff,svg,webp"

Nur wenn man den Link entfernt und komplett neu setzt, dann kann man auch wieder PDF Dateien auswählen.

Mehr eingrenzen kann ich den Fehler nicht, aber er tritt auf verschiedenen Webseiten auf.
(Früher ist mir das nicht aufgefallen, ich kann also nicht sagen ob es mit einem neueren Update zusammen hängt.)

tinymce5 | 1.2.15
REDAXO: 5.13.3 oder 5.14.1
PHP: 7.4.30 oder ähnlich (keine 8er Version)

Getestet im Browser:  Firefox und Chrome

Fragen gerne an mich.

**Comment by TobiasKrais** [comment]
Hab grad einen Fix geschrieben. Kannst du eventuell den Fix gegentesten?
