### ISSUE TITLE
Tiny fügt Html-Kopf ein

### ISSUE THREAD

**Issue by AndiLeni** [FriendsOfREDAXO/tinymce5#5]
Aktuell werden in meiner Seite noch für jeden Tiny-Code die Standard-Kopfzeilen eingefügt.

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
```

**Comment by skerbis** [comment]
Ich kann den Fehler nicht reproduzieren. 
Wie sieht Dein Modul-Code aus?

**Comment by AndiLeni** [comment]
Die Eingabe so:
````
<textarea id="value-1" class="tiny5-editor" data-profile="default" name="REX_INPUT_VALUE[1]">REX_VALUE[1]</textarea>
````

und die Ausgabe so:
```
REX_VALUE[id="1" output="html"]
````

**Comment by skerbis** [comment]
Du hast Recht: 

Die Ausgabe sieht bei mir wie folgt aus: 

```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<p>Das ist ein Test</p>
<p><img src="../media/bildschirmfoto_2019-03-15_um_17.53.00.png" alt="" width="544" height="128" /></p>
</body>
</html>
```

**Comment by skerbis** [comment]
UPDATE: Schuld ist das `fullpage`-PlugIn. Entferne ich dieses jedoch aus dem Profil und der Toolbar, funktioniert das Profil nicht mehr. @joachimdoerr

**Comment by joachimdoerr** [comment]
@skerbis du musst fullpage auch aus der toolbar liste entfernen dann gehts.

**Comment by skerbis** [comment]
siehe vorherigen Kommentar

**Comment by skerbis** [comment]
beta 2
